[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.2"

[functions]
  directory = "functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
